# Generated by Django 4.2.9 on 2025-06-26 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mileage_calculator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traindailyrecord",
            name="daily_mileage",
            field=models.IntegerField(
                blank=True,
                help_text="Дневной пробег в километрах",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Дневной пробег",
            ),
        ),
    ]
